sudo: required
services:
  - docker

before_install: 
  - docker build -t exodiums/react-test -f ./client/Dockerfile.dev ./client

script:
  # this is the command to run the test if any test fails return 1 other than 0  and travis will fail
  - docker run -e CI=true exodiums/react-test npm run test

after_success:
- docker build -t exodiums/multi-client ./client
- docker build -t exodiums/multi-nginx ./nginx
- docker build -t exodiums/multi-server ./server
- docker build -t exodiums/multi-worker ./worker
# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take thoose images and push thme to docker hub
- docker push exodiums/multi-client
- docker push exodiums/multi-nginx
- docker push exodiums/multi-server
- docker push exodiums/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-290746353151"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY